package middleware

import (
	"net/http"
	"strings"

	"github.com/eugenioenko/autentico/pkg/cspnonce"
)

// SecurityHeadersMiddleware adds defense-in-depth HTTP headers recommended by
// OWASP. These prevent clickjacking, MIME sniffing, and restrict embedding.
func SecurityHeadersMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		// Swagger UI and Scalar API docs load scripts from CDNs;
		// skip CSP and caching headers so the documentation renders correctly.
		if strings.HasPrefix(r.URL.Path, "/swagger/") || strings.HasPrefix(r.URL.Path, "/api-docs") {
			next.ServeHTTP(w, r)
			return
		}
		// Prevent clickjacking — disallow framing entirely.
		w.Header().Set("X-Frame-Options", "DENY")

		// Prevent MIME-type sniffing — browser must respect Content-Type.
		w.Header().Set("X-Content-Type-Options", "nosniff")

		// Content Security Policy — restrict scripts to same origin + per-request
		// nonce. The nonce is generated by cspnonce.Middleware (which runs before
		// this middleware in the chain) and injected into every <script> tag via
		// templates. 'unsafe-inline' in style-src is retained because inline
		// styles are lower risk and harder to nonce comprehensively.
		// form-action must allow any origin because the login form redirects to
		// the client's redirect_uri, which is on a different origin. The redirect
		// URI is validated against the registered client in the authorize handler.
		// cdn.jsdelivr.net is allow-listed in style-src/font-src alongside Google
		// Fonts for the retro theme's icon font (themes/retro/account/index.html),
		// which is served as a static file with no template access to the nonce.
		nonce := cspnonce.Get(r.Context())
		scriptSrc := "'self'"
		if nonce != "" {
			scriptSrc = "'self' 'nonce-" + nonce + "'"
		}
		w.Header().Set("Content-Security-Policy", "default-src 'self'; script-src "+scriptSrc+"; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; img-src 'self' data:; font-src 'self' data: https://fonts.gstatic.com https://cdn.jsdelivr.net; connect-src 'self'; form-action *; frame-ancestors 'none'")

		// Permissions Policy — disable browser features not used by the IdP.
		w.Header().Set("Permissions-Policy", "camera=(), microphone=(), geolocation=(), payment=()")

		// Prevent cross-origin embedding.
		w.Header().Set("Cross-Origin-Embedder-Policy", "credentialless")

		// Restrict window references from cross-origin navigations.
		w.Header().Set("Cross-Origin-Opener-Policy", "same-origin")

		// RFC 6749 §5.1 / RFC 6750 §5.3: prevent caching of sensitive responses.
		// Static asset handlers override this with their own Cache-Control values.
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Pragma", "no-cache")

		wrappedWriter := &headerStrippingResponseWriter{ResponseWriter: w}
		next.ServeHTTP(wrappedWriter, r)
	})
}

type headerStrippingResponseWriter struct {
	http.ResponseWriter
}

func (w *headerStrippingResponseWriter) WriteHeader(statusCode int) {
	w.ResponseWriter.Header().Del("Server")
	w.ResponseWriter.Header().Del("X-Powered-By")
	w.ResponseWriter.WriteHeader(statusCode)
}

func (w *headerStrippingResponseWriter) Write(b []byte) (int, error) {
	w.ResponseWriter.Header().Del("Server")
	w.ResponseWriter.Header().Del("X-Powered-By")
	return w.ResponseWriter.Write(b)
}
