package cli

import (
	"crypto/rand"
	"crypto/rsa"
	"encoding/hex"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/joho/godotenv"
	"github.com/urfave/cli/v2"

	"github.com/eugenioenko/autentico/pkg/key"
)

const defaultDbFilePath = "./autentico.db"

type envParams struct {
	appURL        string
	listenPort    string
	dbFilePath    string
	accessSecret  string
	refreshSecret string
	csrfSecret    string
	dbAesKey      string
	privateKeyB64 string
	dev           bool
}

func buildEnvContent(p envParams) string {
	secureCookieValue := "true"
	cookieComment := "# Cookie security — requires HTTPS. Set to false only for local HTTP development."
	if p.dev {
		secureCookieValue = "false"
		cookieComment = "# Cookie security (development mode — HTTP only)\n# WARNING: do NOT use these settings in production; cookies will be sent over plaintext HTTP."
	}

	lines := []string{
		"# Autentico configuration — generated by 'autentico init'",
		"# Keep this file secret and do not commit it to version control.",
		"#",
		"# Settings below cover infrastructure (bootstrap) config that requires a restart to change.",
		"# Runtime settings (token expiry, MFA, SMTP, theme, etc.) are managed via the Admin UI",
		"# and stored in the database — they do not need to be set here.",
		"",
		"# ── Database ────────────────────────────────────────────────────────────────",
		"# Path to the SQLite database file. The directory must exist.",
		fmt.Sprintf("AUTENTICO_DB_FILE_PATH=%s", p.dbFilePath),
		"",
		"# ── Server ──────────────────────────────────────────────────────────────────",
		"# Public base URL of this instance. Used as the OIDC issuer and for building",
		"# redirect URIs. Must include scheme and host. No trailing slash.",
		fmt.Sprintf("AUTENTICO_APP_URL=%s", p.appURL),
		"#",
		"# URL path prefix for all OAuth2/OIDC endpoints.",
		"# The issuer will be AUTENTICO_APP_URL + AUTENTICO_APP_OAUTH_PATH.",
		"AUTENTICO_APP_OAUTH_PATH=/oauth2",
		"#",
		"# Port the server listens on locally. Useful when a reverse proxy handles TLS",
		"# and the public AUTENTICO_APP_URL port differs from the local bind port.",
		fmt.Sprintf("AUTENTICO_LISTEN_PORT=%s", p.listenPort),
		"",
		"# ── Cryptographic secrets ────────────────────────────────────────────────────",
		"# Keep these private. Changing them invalidates existing tokens and sessions.",
		fmt.Sprintf("AUTENTICO_ACCESS_TOKEN_SECRET=%s", p.accessSecret),
		fmt.Sprintf("AUTENTICO_REFRESH_TOKEN_SECRET=%s", p.refreshSecret),
		fmt.Sprintf("AUTENTICO_CSRF_SECRET_KEY=%s", p.csrfSecret),
		fmt.Sprintf("AUTENTICO_DB_AES_KEY=%s", p.dbAesKey),
		"",
		"# ── RSA key for JWT signing ──────────────────────────────────────────────────",
		"# Base64-encoded RSA private key PEM. Used to sign access tokens and ID tokens (RS256).",
		"# If unset, an ephemeral key is generated on each startup — all tokens are invalidated on restart.",
		fmt.Sprintf("AUTENTICO_PRIVATE_KEY=%s", p.privateKeyB64),
		"#",
		"# Key ID included in the JWK Set (/oauth2/.well-known/jwks.json). Change if rotating keys.",
		"AUTENTICO_JWK_CERT_KEY_ID=autentico-key-1",
		"",
		"# ── Cookies ─────────────────────────────────────────────────────────────────",
		cookieComment,
		"#",
		"# CSRF protection cookie. Must be true in production (HTTPS).",
		"# Set to false only when running over plain HTTP (local dev).",
		fmt.Sprintf("AUTENTICO_CSRF_SECURE_COOKIE=%s", secureCookieValue),
		"#",
		"# Name of the refresh token cookie.",
		"AUTENTICO_REFRESH_TOKEN_COOKIE_NAME=autentico_refresh_token",
		"#",
		"# Cookie-only delivery mode: when true, the refresh token is sent as an HttpOnly cookie",
		"# and stripped from the JSON token response. This is a non-standard extension — standard",
		"# OIDC clients expect the refresh token in the response body. Opt-in, defaults to false.",
		"AUTENTICO_REFRESH_TOKEN_COOKIE_ONLY=false",
		"#",
		"# Name and Secure flag for the IdP SSO session cookie.",
		"AUTENTICO_IDP_SESSION_COOKIE_NAME=autentico_idp_session",
		fmt.Sprintf("AUTENTICO_IDP_SESSION_SECURE=%s", secureCookieValue),
		"",
		"# ── Rate limiting ───────────────────────────────────────────────────────────",
		"# Per-IP rate limiting applied to auth endpoints.",
		"# RPS: sustained requests per second allowed per IP. 0 disables.",
		"AUTENTICO_RATE_LIMIT_RPS=5",
		"# BURST: maximum burst size above the RPS limit.",
		"AUTENTICO_RATE_LIMIT_BURST=10",
		"# RPM: sustained requests per minute allowed per IP. 0 disables.",
		"AUTENTICO_RATE_LIMIT_RPM=20",
		"# RPM_BURST: maximum burst size above the RPM limit.",
		"AUTENTICO_RATE_LIMIT_RPM_BURST=20",
		"",
		"# ── Anti-timing delay ────────────────────────────────────────────────────────",
		"# Random delay (milliseconds) added to authentication responses to prevent",
		"# timing-based user enumeration. Set both to 0 to disable (e.g. for profiling).",
		"AUTENTICO_ANTI_TIMING_MIN_MS=50",
		"AUTENTICO_ANTI_TIMING_MAX_MS=150",
		"",
		"# ── Performance tuning ───────────────────────────────────────────────────────",
		"# Number of SQLite read connections in the pool. Reads run concurrently via WAL mode",
		"# while writes serialize through a single connection.",
		"# 0 = auto (whichever is smaller: available CPUs or 4, minimum 2).",
		"# Set explicitly to override (e.g. 8 for read-heavy workloads).",
		"AUTENTICO_DB_READ_POOL_SIZE=0",
	}

	return strings.Join(lines, "\n") + "\n"
}

func RunInit(c *cli.Context) error {
	outputDir := c.String("output")
	envPath := filepath.Join(outputDir, ".env")
	if _, err := os.Stat(envPath); err == nil {
		return fmt.Errorf("%s already exists. Delete it first if you want to reinitialize", envPath)
	}

	appURL := c.String("url")
	if appURL == "" {
		appURL = "http://localhost:9999"
	}
	appURL = strings.TrimRight(appURL, "/")

	u, err := url.Parse(appURL)
	if err != nil {
		return fmt.Errorf("invalid --url: %w", err)
	}
	if u.Scheme == "" || u.Host == "" {
		return fmt.Errorf("--url must include scheme and host, e.g. http://localhost:9999")
	}

	listenPort := u.Port()
	if listenPort == "" {
		if u.Scheme == "https" {
			listenPort = "443"
		} else {
			listenPort = "80"
		}
	}

	accessSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate access token secret: %w", err)
	}
	refreshSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate refresh token secret: %w", err)
	}
	dbAesKey, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate DB AES key: %w", err)
	}
	csrfSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate CSRF secret: %w", err)
	}

	rsaKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return fmt.Errorf("failed to generate RSA key: %w", err)
	}

	dev := c.Bool("dev")
	content := buildEnvContent(envParams{
		appURL:        appURL,
		listenPort:    listenPort,
		dbFilePath:    defaultDbFilePath,
		accessSecret:  accessSecret,
		refreshSecret: refreshSecret,
		csrfSecret:    csrfSecret,
		dbAesKey:      dbAesKey,
		privateKeyB64: key.EncodeKeyToBase64(rsaKey),
		dev:           dev,
	})

	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		return fmt.Errorf("failed to write .env: %w", err)
	}

	fmt.Println(".env file created successfully.")
	fmt.Printf("  App URL:    %s\n", appURL)
	fmt.Printf("  Issuer:     %s/oauth2\n", appURL)
	fmt.Println("")
	if dev {
		fmt.Println("  NOTE: Generated in development mode (--dev).")
		fmt.Println("  Secure cookie flags are disabled for local HTTP use.")
		fmt.Println("  Re-run without --dev for a production configuration.")
		fmt.Println("")
	}
	fmt.Println("Next steps:")
	fmt.Println("  Run 'autentico start' to start the server")

	return nil
}

// autoGenerateConfig generates a .env file in CWD if one does not already exist.
// In Docker, WORKDIR is /app/data (the volume), so .env and DB persist automatically.
// On subsequent runs, the existing .env is loaded and reused.
func autoGenerateConfig(urlFlag string, devFlag bool) error {
	if _, err := os.Stat(".env"); err == nil {
		_ = godotenv.Load(".env")
		return nil
	}

	// Determine the app URL: --url flag > AUTENTICO_APP_URL env var > default.
	appURL := urlFlag
	if appURL == "" {
		appURL = os.Getenv("AUTENTICO_APP_URL")
	}
	if appURL == "" {
		appURL = "http://localhost:9999"
	}
	appURL = strings.TrimRight(appURL, "/")

	u, err := url.Parse(appURL)
	if err != nil {
		return fmt.Errorf("auto-setup: invalid URL: %w", err)
	}

	listenPort := u.Port()
	if listenPort == "" {
		if u.Scheme == "https" {
			listenPort = "443"
		} else {
			listenPort = "80"
		}
	}

	accessSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("auto-setup: failed to generate access token secret: %w", err)
	}
	refreshSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("auto-setup: failed to generate refresh token secret: %w", err)
	}
	dbAesKey, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("failed to generate DB AES key: %w", err)
	}
	csrfSecret, err := randomHex(32)
	if err != nil {
		return fmt.Errorf("auto-setup: failed to generate CSRF secret: %w", err)
	}

	rsaKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return fmt.Errorf("auto-setup: failed to generate RSA key: %w", err)
	}

	dev := devFlag || u.Scheme != "https"
	content := buildEnvContent(envParams{
		appURL:        appURL,
		listenPort:    listenPort,
		dbFilePath:    defaultDbFilePath,
		accessSecret:  accessSecret,
		refreshSecret: refreshSecret,
		csrfSecret:    csrfSecret,
		dbAesKey:      dbAesKey,
		privateKeyB64: key.EncodeKeyToBase64(rsaKey),
		dev:           dev,
	})

	if err := os.WriteFile(".env", []byte(content), 0600); err != nil {
		return fmt.Errorf("auto-setup: failed to write .env: %w", err)
	}

	_ = godotenv.Load(".env")

	fmt.Printf("  Auto-generated configuration: .env\n")
	return nil
}

// randomHex generates n random bytes and returns them as a hex string.
func randomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}
